apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  selector:
    matchLabels:
      app: python
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - image: 553882164358.dkr.ecr.us-east-1.amazonaws.com/python:latest
          imagePullPolicy: Always
          name: python
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3000
              name: python
      imagePullSecrets:
          - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: python-node-port
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: python-node-port
    nodePort: 32700
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: python
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: python-cluster
spec:
  ports:
    - name: python-port
      protocol: TCP
      port: 3000
  selector:
    app: python
  type: ClusterIP
  clusterIP: 10.108.183.83